### ISSUE TITLE
Not compatible with MediaWiki 1.39

### ISSUE THREAD

**Issue by valerio-bozzolan** [teran/mediawiki-GoogleRichCards#10]
First of all, thanks for this extension :)

I just noticed this problem in a MediaWiki 1.39:

```
Original exception: [204287e89e075c8563495d8f] /dico/index.php Error: Call to undefined method Title::getEarliestRevTime()
Backtrace:
from /var/www/dicoado.demo/fr/httpdocs/w/extensions/GoogleRichCards/Article.php(82)
#0 /var/www/dicoado.demo/fr/httpdocs/w/extensions/GoogleRichCards/Article.php(132): MediaWiki\Extension\GoogleRichCards\Article->getCTime()
#1 /var/www/dicoado.demo/fr/httpdocs/w/extensions/GoogleRichCards/Hooks.php(34): MediaWiki\Extension\GoogleRichCards\Article->render()
#2 /var/www/dicoado.demo/fr/httpdocs/w/includes/HookContainer/HookContainer.php(338): MediaWiki\Extension\GoogleRichCards\Hooks::onBeforePageDisplay()
#3 /var/www/dicoado.demo/fr/httpdocs/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 /var/www/dicoado.demo/fr/httpdocs/w/includes/HookContainer/HookRunner.php(946): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/dicoado.demo/fr/httpdocs/w/includes/OutputPage.php(2871): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay()
#6 /var/www/dicoado.demo/fr/httpdocs/w/includes/MediaWiki.php(922): OutputPage->output()
#7 /var/www/dicoado.demo/fr/httpdocs/w/includes/MediaWiki.php(562): MediaWiki->main()
#8 /var/www/dicoado.demo/fr/httpdocs/w/index.php(50): MediaWiki->run()
#9 /var/www/dicoado.demo/fr/httpdocs/w/index.php(46): wfIndexMain()
#10 {main}
```

This is very probably an escalation from this warning:

https://github.com/teran/mediawiki-GoogleRichCards/issues/8

I hope this could give more visibility to the problem, and eventually attract contributors to fix this :)

**Comment by mary-kate** [comment]
Fixed this and some other issues on my forked version, which I've tested against MW 1.43: https://github.com/mary-kate/mediawiki-extensions-GoogleRichCards
